/** Maps DB icon keys (seeded from the prototype) to ids in ui/ikone-sprite.svg. */
const SPRITE: Record<string, string> = {
  welcome: "i-sparkle",
  sparkle: "i-sparkle",
  apart: "i-bed",
  bed: "i-bed",
  pin: "i-pin",
  park: "i-car",
  gate: "i-key",
  gear: "i-sliders",
  clock: "i-clock",
  wifi: "i-wifi",
  doc: "i-book",
  pool: "i-waves",
  sup: "i-waves",
  scooter: "i-disc",
  dumb: "i-dumbbell",
  grill: "i-flame",
  boat: "i-parasol",
  ferry: "i-parasol",
  dice: "i-disc",
  drop: "i-waves",
  ice: "i-sparkle",
  coffee: "i-bread",
  fork: "i-bread",
  cocktail: "i-parasol",
  pizza: "i-flame",
  star: "i-star",
  hike: "i-compass",
  bike: "i-disc",
  beach: "i-parasol",
  culture: "i-book",
  nature: "i-compass",
  map: "i-map",
  party: "i-sparkle",
  cart: "i-cart",
  bread: "i-bread",
  gas: "i-fuel",
  atm: "i-card",
  pharm: "i-cross",
  hosp: "i-hospital",
  home: "i-home",
  bag: "i-bag",
  compass: "i-compass",
  rules: "i-rules",
  chat: "i-chat",
  phone: "i-phone",
};

export function spriteId(icon?: string | null): string {
  if (!icon) return "i-sparkle";
  if (SPRITE[icon]) return SPRITE[icon];
  return icon.startsWith("i-") ? icon : "i-sparkle";
}
