import {
  Sparkles,
  BedDouble,
  MapPin,
  Car,
  KeyRound,
  SlidersHorizontal,
  Clock,
  Wifi,
  ScrollText,
  Waves,
  Bike,
  Dumbbell,
  Flame,
  Ship,
  Sailboat,
  Dices,
  Droplet,
  IceCreamCone,
  Coffee,
  Utensils,
  Martini,
  Pizza,
  Star,
  Mountain,
  Umbrella,
  Landmark,
  Trees,
  Map,
  PartyPopper,
  ShoppingCart,
  Croissant,
  Fuel,
  CreditCard,
  Cross,
  Hospital,
  Home,
  ShoppingBag,
  Compass,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  welcome: Sparkles,
  sparkle: Sparkles,
  apart: BedDouble,
  pin: MapPin,
  park: Car,
  gate: KeyRound,
  gear: SlidersHorizontal,
  sliders: SlidersHorizontal,
  clock: Clock,
  wifi: Wifi,
  doc: ScrollText,
  pool: Waves,
  sup: Waves,
  scooter: Bike,
  dumb: Dumbbell,
  grill: Flame,
  boat: Sailboat,
  ferry: Ship,
  dice: Dices,
  drop: Droplet,
  ice: IceCreamCone,
  coffee: Coffee,
  fork: Utensils,
  cocktail: Martini,
  pizza: Pizza,
  star: Star,
  hike: Mountain,
  bike: Bike,
  beach: Umbrella,
  culture: Landmark,
  nature: Trees,
  map: Map,
  party: PartyPopper,
  cart: ShoppingCart,
  bread: Croissant,
  gas: Fuel,
  atm: CreditCard,
  pharm: Cross,
  hosp: Hospital,
  home: Home,
  bag: ShoppingBag,
  compass: Compass,
};

export function CategoryIcon({
  name,
  className,
}: {
  name?: string | null;
  className?: string;
}) {
  const Icon = (name && ICONS[name]) || Sparkles;
  return <Icon className={className} aria-hidden="true" />;
}
